# fly.toml app configuration file generated for auth-frosty-butterfly-5873 on 2025-01-13T23:23:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'auth-frosty-butterfly-5873'
primary_region = 'ewr'

[build]
  image = 'registry.supertokens.io/supertokens/supertokens-postgresql'

[http_service]
  internal_port = 3567
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
